import type { Metadata } from 'next';
import { geistMono, geistSans } from './fonts/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'StartClinch',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
